name = "duke-worker"
main = "src/worker.ts"
compatibility_date = "2026-03-01"

[[d1_databases]]
binding = "DB"
database_name = "duke_logs"
database_id = "6142a82f-0360-450d-924a-edbc54190a1e"

[assets]
directory = "./src/public"
binding = "ASSETS"
